sed -i "/part19822/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13463/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16229/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16399/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23492/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part12856/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13226/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23364/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13413/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18184/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18641/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23494/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23362/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14718/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19060/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15426/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16686/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23499/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17149/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part12983/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15615/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13472/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17974/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19370/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16123/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14208/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15247/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part12809/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16038/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13629/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17361/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16522/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14260/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14382/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16414/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14307/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13402/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16227/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13275/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15084/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16578/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18952/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17396/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17315/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15966/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part21286/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16592/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17814/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14431/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13399/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19782/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16450/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13940/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15558/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17777/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15389/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19762/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19794/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18807/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13155/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18943/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18320/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14892/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18032/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14026/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18831/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19227/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17247/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17236/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19929/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15554/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19488/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19581/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13923/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15225/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13542/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17292/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15467/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13160/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19556/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14617/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16796/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13666/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15777/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17138/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13320/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17038/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19082/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18565/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16613/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15475/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part12799/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18475/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16809/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14349/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13434/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16163/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15767/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18204/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19810/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14117/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14139/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16261/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14331/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14610/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16871/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18828/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17591/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17812/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16444/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15994/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15688/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19257/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14149/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17115/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15998/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19211/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17183/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13945/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16138/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15988/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17279/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15841/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13427/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16629/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18574/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16605/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18753/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15635/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18922/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15259/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19936/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17060/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17087/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17627/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18119/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16574/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18840/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19905/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18256/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19350/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18791/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part20158/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18452/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14920/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19708/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14926/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17275/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16166/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14216/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13632/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16323/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15668/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15922/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15569/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17108/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14120/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17036/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19107/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18652/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14990/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14471/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15287/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15623/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16176/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17609/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16105/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14259/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15537/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17624/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16807/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18222/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18685/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17372/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16313/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14054/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part12818/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13329/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18060/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17450/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13416/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15784/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16191/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19141/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16222/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15726/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14185/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18568/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19454/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18936/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15925/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part12909/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16408/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16664/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18096/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14821/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16970/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13543/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23606/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14725/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19323/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13680/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18997/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14637/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13180/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15964/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15454/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19386/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13947/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part20259/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14970/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part21239/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15474/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part20630/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14668/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17849/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15999/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part20159/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14086/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18811/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part20940/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part22883/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part12836/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16755/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part20845/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13780/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part21918/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16448/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14345/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17984/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18263/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14220/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16390/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15535/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23608/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13625/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part12916/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13779/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part20712/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part20476/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part21044/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part21019/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13073/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23593/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17517/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16501/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18958/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17398/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14730/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23579/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15564/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14597/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part12803/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part12927/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18610/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23614/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23596/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15481/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13288/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17181/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16939/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16158/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part21492/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part12886/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16670/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18067/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23631/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23610/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13251/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23634/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17862/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14008/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15246/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23577/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16764/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13697/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18842/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part21042/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23601/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14140/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part17686/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15974/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23589/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16991/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16699/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18397/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23611/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19166/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23638/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23615/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23591/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part22868/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18818/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part18881/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15025/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14853/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19116/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14336/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16541/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part13039/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19453/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16867/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16786/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part14841/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15329/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part20410/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15073/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part15632/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part16048/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part12928/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part19823/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part12951/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23618/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23600/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part22782/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
sed -i "/part23040/d" /n/holyscratch01/extavour_lab/shchurch/assembly_phylogeny_expression_Hawaiian_Drosophila_June2021/agalma/reports/59.supermatrix.partition.nex
